name: Release

on:
  push:
    tags:
      - 'v*' # Trigger on tags starting with v (e.g. v1.0)

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run Tests
      uses: ./.github/actions/build-test-lint
      with:
        SPS_API_TOKEN: ${{ secrets.SPS_API_TOKEN }}
        SPS_API_WRITE_TOKEN: ${{ secrets.SPS_API_WRITE_TOKEN }}
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        VRCHAT_USERNAME: ${{ secrets.VRCHAT_USERNAME }}
        VRCHAT_PASSWORD: ${{ secrets.VRCHAT_PASSWORD }}
        VRCHAT_COOKIE: ${{ secrets.VRCHAT_COOKIE }}

    - name: Run build script
      run: "./release/release-build.sh"

    - name: Generate changelog
      id: changelog
      run: |
        ./release/generate-changelog.sh "${{ github.ref_name }}" RELEASE_NOTES.md
        echo "notes_file=RELEASE_NOTES.md" >> $GITHUB_OUTPUT
        
        IS_PRERELEASE="$( [[ "${{ github.ref_name }}" == *"-"* ]] && echo "true" || echo "false" )"
        echo "IS_PRERELEASE=$IS_PRERELEASE" >> $GITHUB_ENV

    - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.DEPLOY_TOKEN }}
        files: "target/release_builds/*"
        body_path: ${{ steps.changelog.outputs.notes_file }}
        prerelease: ${{ env.IS_PRERELEASE }}
